services:
  - type: web
    name: pathai-sam2
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt && pip install git+https://github.com/facebookresearch/sam2.git
    startCommand: gunicorn --bind 0.0.0.0:$PORT codeR:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PORT
        value: 10000
    healthCheckPath: /
